name: e2b
description: "A compact dictionary both E2E and E2B"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/HindSiliguri-Regular.ttf
  fonts:
    - family: HindSiliguri
      fonts:
        - asset: assets/fonts/HindSiliguri-Regular.ttf

flutter_icons:
  android: true
  # ios: true
  image_path: "assets/icon/e2e.png"